scraper:
  urls: https://blog.osservatori.net/it_it/tag/innovative-payments;https://www.pagamentidigitali.it/payment-innovation/;https://www.pagamentidigitali.it/payment-services/;https://www.pagamentidigitali.it/mobile-app/;https://www.corrierecomunicazioni.it/digital-economy/;https://www.ilsole24ore.com/sez/tecnologia/fintech;https://www.paymentscardsandmobile.com/category/mobile-payments/;https://fintechmagazine.com/digital-payments/articles
  page.limit: 100

spring:
  datasource:
    url: "jdbc:postgresql://localhost:54320/postgres"
    username: postgres
    password: password
  jpa.hibernate.ddl-auto: validate


website:
  map:
    blog_osservatori:
      url: "https://blog.osservatori.net/it_it/tag/innovative-payments"
      title: ".//h2"
      image: ".//div[contains(@class,'hs-featured-image-wrapper')]"
      link: ".//h2//a"
      items: "//div[contains(@class,'post-item-inner')]"
      date: ".//span[contains(@class,'custom-date')]"
      dateFormatter: "dd MMMM yyyy"
      dateLocale: en
      category: ".//p[contains(@id,'hubspot-topic_data')]"
      body: ".//div[contains(@class,'post-body')]"
      nextPage: "//a[@class ='next-link']"
      key: "blog_osservatori"
    pagamentidigitali_innovation:
      url: "https://www.pagamentidigitali.it/payment-innovation/"
      title: ".//h3[contains(@class,'entry-title')]"
      image: ".//img"
      link: ".//a"
      items: "//article"
      date: ".//span[contains(@class,'mh-meta-date')]"
      dateFormatter: "dd MMMM yyyy"
      dateLocale: it
      category: ".//div[contains(@class,'mh-image-caption')]"
      body: ".//div[contains(@class,'mh-excerpt')]"
      nextPage: "//a[@class = 'next page-numbers']"
      key: "pagamentidigitali_innovation"
    pagamentidigitali_services:
      url: "https://www.pagamentidigitali.it/payment-services/"
      title: ".//h3[contains(@class,'entry-title')]"
      image: ".//img"
      link: ".//a"
      items: "//article"
      date: ".//span[contains(@class,'mh-meta-date')]"
      dateFormatter: "dd MMMM yyyy"
      dateLocale: it
      category: ""
      body: ".//div[contains(@class,'mh-excerpt')]"
      nextPage: "//a[@class = 'next page-numbers']"
      key: "pagamentidigitali_services"
    pagamentidigitali_mobile:
      url: "https://www.pagamentidigitali.it/mobile-app/"
      title: ".//h3[contains(@class,'entry-title')]"
      image: ".//img"
      link: ".//a"
      items: "//article"
      date: ".//span[contains(@class,'mh-meta-date')]"
      dateFormatter: "dd MMMM yyyy"
      dateLocale: it
      category: ".//div[contains(@class,'mh-image-caption')]"
      body: ".//div[contains(@class,'mh-excerpt')]"
      nextPage: "//a[@class = 'next page-numbers']"
      key: "pagamentidigitali_mobile"
    corriere:
      url: "https://www.corrierecomunicazioni.it/digital-economy/"
      title: ".//h2[contains(@class,'title')]|.//h1[contains(@class,'title')]"
      image: ".//img"
      link: ".//a[.//div[contains(@class,'card')]]"
      items: "//li[contains(@class,'collection-item')][.//a]|//div[contains(@class,'card-large')][.//a]|//div[contains(@class,'card-post')][.//a[contains(@class,'flex-column')]]"
      date: ".//p[contains(@class,'data')]"
      dateFormatter: "dd MMM yyyy"
      dateLocale: it
      category: ".//h4[contains(@class,'card-post__occhiello')]|.//p[contains(@class,'occhiello')]"
      body: ""
      nextPage: "//div[contains(@class,'pagination-box')]/a[./i[contains(@data-icon,'keyboard_arrow_right')]]"
      key: "corriere"
    sole24ore:
      url: "https://www.ilsole24ore.com/sez/tecnologia/fintech"
      title: ".//h3"
      image: ".//figure//img"
      link: ".//a"
      items: "//div[contains(@class,'col-lg-8')]//li[contains(@class,'list-lined-item')]"
      date: ".//time"
      dateFormatter: "dd/MM/yyyy"
      dateLocale: it
      category: ".//p[contains(@class,'meta')]//a"
      body: ""
      nextPage: "//a[@class = 'pager-link '][./span[contains(@class,'icon-arrow-right')]]|//div[@class = 'text-right']/a[@class = 'btn btn--big']"
      key: "sole24ore"
    paymentscardsandmobile:
      url: "https://www.paymentscardsandmobile.com/category/mobile-payments/"
      title: ".//h2|.//a[contains(@class,'trending_ntitle')]"
      image: ".//img"
      link: ".//a"
      items: "//div[contains(@class,'single_article')]|//div[contains(@class,'single_training')]"
      date: ".//p[contains(@class,'datetime')]"
      dateFormatter: "dd MMM yy '@' hh:mm"
      dateLocale: en
      category: ""
      body: ".//p[contains(@class,'news_excerpt')]"
      nextPage: "//div[@class = 'pagination']/ul/li[last() - 1]/a"
      key: "paymentscardsandmobile"

