scraper.urls: https://blog.osservatori.net/it_it/tag/innovative-payments;https://www.pagamentidigitali.it/payment-innovation/;https://www.pagamentidigitali.it/payment-services/;https://www.pagamentidigitali.it/mobile-app/;https://www.corrierecomunicazioni.it/digital-economy/;https://www.ilsole24ore.com/sez/tecnologia/fintech;https://www.paymentscardsandmobile.com/category/mobile-payments/;https://fintechmagazine.com/digital-payments/articles

spring:
  datasource:
    url: "jdbc:postgresql://localhost:54320/postgres"
    username: postgres
    password: password
  jpa.hibernate.ddl-auto: validate


website:
  map:
    blog_osservatori:
      url: "https://blog.osservatori.net/it_it/tag/innovative-payments"
      title: "//h2"
      image: "//div[contains(@class,'hs-featured-image-wrapper')]"
      link: "//a"
      items: "//div[contains(@class,'post-item-inner')]"
      date: "//span[contains(@class,'custom-date')]"
      dateFormatter: "dd MMMM yyyy"
      body: "//div[contains(@class,'post-body')]"
      key: "blog_osservatori"
    pagamentidigitali_innovation:
      url: "https://www.pagamentidigitali.it/payment-innovation/"
      title: "//h3[contains(@class,'entry-title')]"
      image: "//img"
      link: "//a"
      items: "//article"
      date: "//span[contains(@class,'mh-meta-date')]"
      dateFormatter: "dd MMMM yyyy"
      body: "//div[contains(@class,'mh-excerpt')]"
      key: "pagamentidigitali_innovation"
    pagamentidigitali_services:
      url: "https://www.pagamentidigitali.it/payment-services/"
      title: "//h3[contains(@class,'entry-title')]"
      image: "//img"
      link: "//a"
      items: "//article"
      date: "//span[contains(@class,'mh-meta-date')]"
      dateFormatter: "dd MMMM yyyy"
      body: "//div[contains(@class,'mh-excerpt')]"
      key: "pagamentidigitali_services"
    pagamentidigitali_mobile:
      url: "https://www.pagamentidigitali.it/mobile-app/"
      title: "//h3[contains(@class,'entry-title')]"
      image: "//img"
      link: "//a"
      items: "//article"
      date: "//span[contains(@class,'mh-meta-date')]"
      dateFormatter: "dd MMMM yyyy"
      body: "//div[contains(@class,'mh-excerpt')]"
      key: "pagamentidigitali_mobile"
    corriere:
      url: "https://www.corrierecomunicazioni.it/digital-economy/"
      title: "//h2[contains(@class,'title')]|//h1[contains(@class,'title')]"
      image: "//img"
      link: "//a"
      items: "//li[contains(@class,'collection-item')]//a|//div[contains(@class,'card-large__overlay')]|//div[contains(@class,'card-post')]//a[contains(@class,'flex-column')]"
      date: "//p[contains(@class,'data')]"
      dateFormatter: "dd MMM yyyy"
      body: ""
      key: "corriere"
    sole24ore:
      url: "https://www.ilsole24ore.com/sez/tecnologia/fintech"
      title: "//h3"
      image: "//figure//img"
      link: "//a"
      items: "//div[contains(@class,'col-lg-8')]//li[contains(@class,'list-lined-item')]"
      date: "//time"
      dateFormatter: "dd/MM/yyyy"
      body: ""
      key: "sole24ore"
    paymentscardsandmobile:
      url: "https://www.paymentscardsandmobile.com/category/mobile-payments/"
      title: "//h2|//a[contains(@class,'trending_ntitle')]"
      image: "//img"
      link: "//a"
      items: "//div[contains(@class,'single_article')]|//div[contains(@class,'single_training')]"
      date: "//p[contains(@class,'datetime')]"
      dateFormatter: "dd MMM yy '@' hh:mm"
      body: "//h2[@class=h2-blog-card]"
      key: "paymentscardsandmobile"
    fintechmagazine:
      url: "https://fintechmagazine.com/digital-payments/articles"
      title: "//h3"
      image: "//img"
      link: "//a[contains(@class,'Card_CardOverlayLink')]"
      items: "//div[contains(@class,'Card_CardWrapper')]"
      date: ""
      dateFormatter: ""
      body: "//div[contains(@class,'Card_CardDescription')]//p"
      key: "fintechmagazine"

